### ISSUE TITLE
Does this work locally?

### ISSUE THREAD

**Issue by rdearman** [Specy/asm-editor#13]
I downloaded this locally... how do I run it? When I open 'app.html' in the browser I just get

%sveltekit.head%
%sveltekit.body%

**Comment by Specy** [comment]
Yes you can run it locally, to make it work you need to "compile" the source code first, i should have put a building section in the repo

To compile you have to:
- have installed (node.js)[https://nodejs.org/en] (including npm)
- go to the folder of the project and run the command `npm i` to install the dependencies
- then build the source code with `npm run build`

A static website will be built in the `/dist` folder, I'm not sure if you can run it by simply clicking the index.html in the dist folder, as maybe the website expects to be running on a server, in that case, you can run the server using `npm run start`

**Comment by rdearman** [comment]
That is ok, I was putting it into a docker container anyway, so once I get it built I will have a webserver. 

The npm -i failed. 
npm -v = 8.5.1

[2024-01-11T17_24_34_613Z-debug-0.log](https://github.com/Specy/asm-editor/files/13906473/2024-01-11T17_24_34_613Z-debug-0.log)

npm ERR! code 1
npm ERR! path /var/docker/68000/asm-editor/node_modules/@sveltejs/kit
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! file:///var/docker/68000/asm-editor/node_modules/@sveltejs/kit/postinstall.js:7
npm ERR! 	const cwd = process.env.INIT_CWD ?? process.cwd();
npm ERR! 	                                  ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)

I re-ran it with sudo just to make sure it wasn't a permissions thing. But it isn't.

**Comment by Specy** [comment]
What version of node are you using `node -v`, that looks like an error from a old node version.
I'm currently using v20, but i think it should work with anything above 18

**Comment by rdearman** [comment]
I upgraded to the latest version 20.10.0 and it is working now.

**Comment by Specy** [comment]
Good! I'll update the readme one of those days to add an installation section, I guess the issue was completed so I'll close it, reopen if needed
