### ISSUE TITLE
post increment addressing mode works correctly?

### ISSUE THREAD

**Issue by karwatka** [Specy/asm-editor#14]
Does post increment addressing mode works properly?
When traced execution of a program
   LEA     $1200,A0       
   MOVEQ   #$55,D2        
   EOR.B   D2,(A0)+
and changed memory view to address $1200, noticed that the last instruction worked as "pre increment", not "post increment", because of changing value under $1201, not $1200 address.

**Comment by Specy** [comment]
Ah yes i just noticed this, i tried to test it on Easy68K and it wrote to 1200 as expected
I found the affected code
increment of post increment: [here](https://github.com/Specy/s68k/blob/f8df0454b342747fef0091195523b16dad19de1f/src/interpreter.rs#L1398)
eor instruction: [here](https://github.com/Specy/s68k/blob/f8df0454b342747fef0091195523b16dad19de1f/src/interpreter.rs#L1011)
The issue being that the register is read (and incremented) and then written (not incremented) while it should be the opposite

i'm a bit busy lately so might take a bit to fix the bug, thanks for letting me know though!

**Comment by Specy** [comment]
Yup i'm doign the fix now! it was way easier than i expected, i should be finished in a few hours.

Just for curiosity, why are you writing m68k? is it for some sort of lectures or just for fun?

**Comment by Specy** [comment]
![image](https://github.com/Specy/asm-editor/assets/59029985/e538a365-0599-4c9d-a603-2a40bb8a1d60)
Seems to be working! I just published the changes

**Comment by karwatka** [comment]
> Yup i'm doing the fix now! it was way easier than i expected, i should be finished in a few hours.
> 
> Just for curiosity, why are you writing m68k? is it for some sort of lectures or just for fun?

Years ago I did a lot of coding in 68K, now I use it to teach students processor programming.
Checked, now works properly:) Thanx a lot!

**Comment by Specy** [comment]
> Years ago I did a lot of coding in 68K, now I use it to teach students processor programming

That's the whole reason why i made the interpreter, the learning curve for assembly is so steep at the beginning because of the lack of "easy to use" tools to teach the basics, i'm glad it's been useful.

Thanks again for the bug report! It also made me spot a similar bug which i fixed
