### ISSUE TITLE
Add movem instruction

### ISSUE THREAD

**Issue by bubbob42** [Specy/asm-editor#18]
Add movem instruction to allow for e.g.

movem.l d0-d7/a0-a6,-(sp)

Great tool, thank you very much!

**Comment by Specy** [comment]
Oh I had complete forgotten about this instruction, I'll add it yes

**Comment by Specy** [comment]
https://github.com/prb28/m68k-instructions-documentation/blob/master/instructions/movem.md

Time to add a new addressing mode I guess!

**Comment by Specy** [comment]
I've added the MOVEM instruction to the interpreter in commit https://github.com/Specy/s68k/commit/ae9dd6b9a63598c0aadaa326e5996a30d42a1ce7, and added in the website in commit https://github.com/Specy/asm-editor/commit/db80cf340474929e27758c162af1d4d92736e9ea.

Here is an example of it working in the documentation https://asm-editor.specy.app/documentation/m68k/instruction/movem

Let me know if it all works as expected! This one was a bit tricky to implement

Also for curiosity, how did you find about the app?

**Comment by bubbob42** [comment]
Hi!Thank you for adding movem! Your app was mentioned on www.amiga-news.de, which I visit regularly. Don’t have much time for 68k asm these days, so your project is perfect for a bit of coding during breaks.Best regardsMarcus Sent from mobile device Am 26.06.2024 um 16:20 schrieb Specy ***@***.***>:﻿
I've added the MOVEM instruction to the interpreter in commit ***@***.***, and added in the website in commit db80cf3.
Here is an example of it working in the documentation https://asm-editor.specy.app/documentation/m68k/instruction/movem
Let me know if it all works as expected! This one was a bit tricky to implement
Also for curiosity, how did you find about the app?

**Comment by Specy** [comment]
Thanks for the info! I'll be closing this issue as completed, if you have any issues/questions let me know
