### ISSUE TITLE
Add `title` to icons

### ISSUE THREAD

**Issue by benmccann** [Specy/asm-editor#4]
The site gets a nearly perfect Lighthouse score! It'd be cool to add a `title` to the `a` and `button` icons to get a perfect score on the accessibility portion as well: https://pagespeed.web.dev/report?url=https%3A%2F%2Fasm-editor.specy.app%2F

**Comment by Specy** [comment]
Done!

**Comment by benmccann** [comment]
Amazing!

Btw, if you hadn't noticed, we added the site as an example on the SvelteKit homepage!

**Comment by Specy** [comment]
> Amazing!
> 
> Btw, if you hadn't noticed, we added the site as an example on the SvelteKit homepage!

Yup i just saw, thanks for the shout-out ^^
